name: "publish to npm"

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "setup:bun"
        uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build
      - uses: actions/setup-node@v4
        with:
          node-version: "21.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
